---
title: "Anti-Trans Laws and Mental Health: Visualizations"
format: html
editor: visual
---

making some visualizations for the poster presentation

```{r}
library(tidyverse)
library(here)
library(colorspace)
library(did)
load(here("data_clean", "hps_data.Rdata"))
load(here("data_clean", "analytic_datasets_trans.Rdata"))
load(here("did_results", "didt_te.Rdata"))
load(here("data_clean", "laws.Rdata"))
```

first, here's a visualization of when states passed anti-trans laws

```{r}
mapdata <- tibble(map_data("state"))

lawsdata <- laws |> 
  group_by(state_name, type) |> 
  summarize(n = n()) |> 
  pivot_wider(id_cols = "state_name",
              names_from = "type",
              values_from = "n",
              values_fill = 0) |> 
  mutate(state_name = tolower(state_name),
         laws_total = bathroom + medical + sports) |> 
  right_join(mapdata, by = c("state_name" = "region")) |> 
  mutate(laws_total = if_else(is.na(laws_total), 0, laws_total))
  

ggplot(data = lawsdata) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = laws_total), color = "black", size = .3) +
  coord_map(projection = "albers", lat0 = 25, lat1 = 49) +
  scale_fill_continuous_sequential(palette = "Reds 3") +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(fill = "Number of\nAnti-Trans Laws\nPassed Since 2016")


```

average treatment effect visualization

```{r}


ggdid(didt_te_2) +
  labs(x = "Waves Since First Anti-Trans Law Passed in State",
       y = "Aggregated Treatment Effect",
       title = "") +
  scale_color_manual(values = c("royalblue", "tomato"),
                     labels = c("Pre", "Post")) +
  geom_vline(xintercept = -.5, linetype = "dashed") +
  geom_hline(yintercept = 0) +
  geom_segment(aes(x = -.5, xend = 10.5, y = 1.4151), color = "tomato",
               linetype = "dotted") +
  geom_text(x = 11.5, y = 1.4151, label = "Overall\nATT *", color = "tomato") +
  theme(plot.margin = unit(c(1,1,1,1), "cm")) +
  coord_cartesian(clip = "off")
```

trends in phq-4 visualization

```{r}
hps_data |> 
  filter(time < 31) |> 
  select(time, anxious, worry, interest, down, trans_gnc, queer, pweight) |>
  mutate(phq4 = anxious + worry + interest + down - 4) |> 
  drop_na(trans_gnc, queer, phq4) |> 
  mutate(group = case_when(queer == 0 & trans_gnc == 0 ~ "Cisgender Heterosexual",
                           queer == 1 & trans_gnc == 0 ~ "Cisgender Queer",
                           trans_gnc == 1 ~ "Trans/Gender Non-Conforming")) |> 
  group_by(time, group) |> 
  summarize(mean_phq = weighted.mean(phq4, w = pweight)) |> 
  ggplot(aes(x = time, y = mean_phq, group = group, color = group)) +
  geom_line() +
  labs(x = "Wave",
       y = "Average PHQ-4 Score",
       color = "") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("tomato", "royalblue", "purple4"))
```

```{r}

```
