---
title: "Anti-Trans Legislation and Mental Health Across U.S. States, 2021-2023."
author: "AP Pittman, Sociology Ph.D. Candidate, Duke University"
subtitle: "Formatted for Submission to JAMA"
format: pdf
bibliography: references.bib
---

## Key Points

### Question

What is the impact of anti-trans laws on the mental health of transgender and gender non-conforming individuals in the United States? Is this impact different for trans/GNC individuals, as compared to their cisgender LGBQ counterparts?

### Findings

The first anti-trans law to pass in a state is associated with a 1.38-point (95% CI: 0.64 to 2.13) increase in PHQ-4 scores among transgender and gender non-conforming individuals compared to cisgender LGBQ individuals in that state. This effect is specific to the *first* anti-trans law to pass in a state, regardless of its focus (bathroom bills, sports bans, or medical care bans).

### Meaning

If providers are interested in reducing symptoms of anxiety and depression among trans/GNC individuals in their state, advocating against *all* forms of anti-trans legislation (rather than simply medical care bans) is important.

\pagebreak

## Abstract

### Importance

The wave of anti-trans legislation across the country is only accelerating. Population mental health impacts of these laws have been speculated, but evidence is lacking.

### Objective

Estimate the impact of the passage of anti-trans laws on anxiety and depressive symptoms among trans and gender non-conforming individuals.

### Design, Setting, Participants

This study utilizes the nationally representative Household Pulse Survey - specifically, thirty waves of data between July 2021 and October 2023 - to estimate staggered difference-in-differences models of anxiety and depressive symptoms among trans/GNC individuals compared to cisgender LGBQ individuals. Participants were grouped based on the timing of anti-trans law passage in the state which they reported living in at the time of the survey.

### Exposure

Passage of an anti-trans law in a participant's state.

### Main Outcome and Measures

The outcome of interest in this study is the PHQ-4 score, which combines answers to four questions about anxiety and depressive symptoms into a single score, ranging from 0-12.

### Results

The first anti-trans law to pass in a state is associated with a 1.38-point (95% CI: 0.64 to 2.13) increase in PHQ-4 scores among trans/GNC individuals compared to their cisgender LGBQ counterparts.

### Conclusions and Relevance

Trans/GNC individuals are uniquely vulnerable to legislative changes, above and beyond even their cisgender LGBQ counterparts. If providers are interested in reducing symptoms of anxiety and depression among trans/GNC individuals in their state, advocating against *all* forms of anti-trans legislation (rather than simply medical care bans) is important.

\pagebreak

## Introduction (300-500 words; currently 298)

According to Trans Legislation Tracker, over 1,000 anti-trans bills were proposed in 2025 across the United States. This is an acceleration from previous years: Trans Legislation Tracker tracked 153 anti-trans bills in 2021, 174 in 2022, 615 in 2023, and 701 in 2024 [@transle]. Small-scale studies have confirmed that these bills have measurable mental health effects on trans and gender non-conforming (GNC) individuals; one study in Washington state, for example, found that trans individuals who were concerned about "having their rights taken away" had higher odds of screening positive for depression and anxiety symptoms, while individuals who were aware of Washington's protective legislation had *lower* odds of the same [@restar2024]. Another study in Massachusetts found similar results for the introduction of "bathroom bills" through legislative referendum [@horne_etal22]. State contexts may also exacerbate individual-level risk factors: for individuals who are aware of anti-trans legislative efforts at the state level, discrimination becomes a stronger predictor of hopelessness and, subsequently, anxiety and depressive symptoms [@tebbe2022]. Despite these important research efforts, little is known about the *population-level* mental health effects of anti-trans legislation. Preeminent sociological and public health scholarship agrees that anti-trans laws are a facet of institutional oppression of trans and GNC individuals; and yet, little research exists connecting these exposures to population health outcomes [@zubizarreta2025; @barbee2022]. One barrier to addressing this gap is data availability: very few population surveys include trans and GNC individuals in sufficient numbers to draw robust conclusions. In an effort to address this gap in the literature, the present study uses what is perhaps the largest available sample of trans and GNC individuals - through the Census Bureau's Household Pulse Survey - to investigate the effect of anti-trans legislation on trans and GNC individual's mental health compared to their cisgender LGBQ counterparts using a difference-in-differences methodology.

## Data and Methods (1000-1500 words)

### Variables and Data Sources

### Analytic Strategy

## Results (1500-2000 words)

### Descriptive

### Difference-in-Differences Analysis

## Discussion and Conclusion (500-700 words)

## References
